// Repo-tracked Start Here shortcut snapshot.
// Replace this file by exporting a fresh snapshot from the extension UI, then commit it.

const SYNC_SHORTCUTS_SOURCE_ID = 'tab-out-sync';
const SYNC_SHORTCUTS = [
  {
    id: 'local-shortcut-1',
    title: 'Gmail',
    url: 'https://mail.google.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-2',
    title: 'Scopus',
    url: 'https://www.scopus.com/pages/home?display=basic#basic',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-3',
    title: 'Perplexity',
    url: 'https://www.perplexity.ai/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-4',
    title: 'G-Scholar',
    url: 'https://scholar.google.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-5',
    title: 'bilibili',
    url: 'https://www.bilibili.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-6',
    title: 'Inoreader',
    url: 'https://www.inoreader.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-7',
    title: 'UQ Library',
    url: 'https://www.library.uq.edu.au/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-8',
    title: 'NotebookLM',
    url: 'https://notebooklm.google.com/?hl=en',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-9',
    title: 'Claude',
    url: 'https://claude.ai/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-10',
    title: 'Blackboard',
    url: 'https://learn.uq.edu.au/ultra/course',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-11',
    title: 'Gemini',
    url: 'https://gemini.google.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-12',
    title: 'ChatGPT',
    url: 'https://chatgpt.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-13',
    title: 'GitHub',
    url: 'https://github.com/Xiaotian-Liu-MKT',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
  {
    id: 'local-shortcut-14',
    title: 'Prolific',
    url: 'https://app.prolific.com/',
    logoMode: 'auto',
    logoDataUrl: '',
    logoTransform: { scale: 1, offsetX: 0, offsetY: 0 },
  },
];
